import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import Plant from "../components/Plant";
export default function Home() {
  const [plants, setPlants] = useState([]);
  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch("/api/plants", {
        method: "GET",
      });
      const dataRes = await response.json();
      setPlants(dataRes);
    };
    fetchData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Plant App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Plants</h1>
        <div className={styles.grid}>
          {plants.map((plant) => {
            return <Plant name={plant.name} care={plant.care} />;
          })}
        </div>
      </main>
    </div>
  );
}
